### ISSUE TITLE
suggestion: using znnedi3/nnedi3cl instead of nnedi3

### ISSUE THREAD

**Issue by Selur** [fdar0536/VapourSynth-Contra-Sharpen-mod#1]
Stumbled over this repository and since it's still active I thought I that using znedi3 (https://github.com/sekrit-twc/znedi3) and/or nnedi3cl (https://github.com/HomeOfVapourSynthEvolution/VapourSynth-NNEDI3CL) 
by adding a 'opencl' (+ may be a 'device'-) parameter and then instead of using:
```
 core.nnedi3.nnedi3(...)
```
using somthing like:
```
    if opencl :
      return core.nnedi3cl.NNEDI3CL(..)
    elif hasattr(core, 'znedi3'):
      return core.znedi3.nnedi3(...)
    else:
      return core.nnedi3.nnedi3(...)
```
(could be stuffed into a function to limit the needed code adjustment)
should speed up the nnedi3 parts of the script quite a bit

**Comment by fdar0536** [comment]
Added. Thanks.
